version: '3.8'

services:
  robot-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3007:3007"
    environment:
      - MCP_HOST=0.0.0.0
      - MCP_PORT=3007
      - ALLOWED_ORIGINS=*
      # Chrome settings
      - PYTHONUNBUFFERED=1
      - DISPLAY=:99
    volumes:
      # Mount local directories to container directories
      - ./output:/app/output                # For generated output files
      - ./tests:/app/tests                  # For test files
      - ./reports:/app/reports              # For test reports
      - /home/suyodhan:/app/local           # Access your home directory via /app/local
    shm_size: 2gb
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3007/sse"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s 